### ISSUE TITLE
Accès pour push l'exo

### ISSUE THREAD

**Issue by olga-bouin** [AlaAtrash/storeApp#1]
Bonjour @AlaAtrash 

Pourriez-vous me donner l'accès à ce projet ?

J'obtiens cette erreur en tirant une branche :

> storeApp [branch] master ❯ git checkout -b olga-komirenko
> Switched to a new branch 'olga-komirenko'
> storeApp [branch] olga-komirenko ❯ git push
> ERROR: Permission to AlaAtrash/storeApp.git denied to 20002283.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

Merci d'avance,
Olga

**Comment by AlaAtrash** [comment]
Bonjour C'est fait !

**Comment by olga-bouin** [comment]
Merci beaucoup
